### ISSUE TITLE
TLS/SSL and twistd?

### ISSUE THREAD

**Issue by luhkevin** [twisted/klein#105]
I want to run klein with https, and I've read the doc here: http://klein.readthedocs.org/en/latest/introduction/2-twistdtap.html

Unless I'm mistaken, this is using twistd to start a klein app  by passing it to --class:

```
      --class=            Create a Resource subclass with a zero-argument
                          constructor.
```

But what if I want to pass arguments to my klein app? How would that work with twistd?

**Comment by notoriousno** [comment]
I'm not entirely sure which one you mean, so I've provided 2 possible answers.

Passing Args to Klein Obj
----------------------------------
You can pass arguments into the ``Klein`` obj and then expose the underlaying Twisted ``Resource``.  For example, let's say you overloaded a Klein obj, you could then pass args into that object :
```
# twistdPlugin.py
app = OverloadedKlein('arg', 'arg', 'arg')

@app.route('/')
def home(r):
    return 'hello'

resource = app.resource
```

Then just run the ``twistd`` script as usual.


Passing Args via CLI
----------------------------
```
# Example:
$> twistd -n web --class=twistdPlugin.resource --arg1 --arg2 --arg3
```

This is a bigger undertaking (but not by much).  You basically have to write a ``twistd plugin``.  I'll provide some Stackoverflow questions so that you have some basic understanding.  Plugins are less intimidating than they sound and it doesn't take too much effort.

- http://stackoverflow.com/questions/15098827/when-launching-a-twisted-application-via-twistd-how-to-send-command-line-argume
- http://stackoverflow.com/questions/18244050/twistd-using-usage-options-in-a-tac-file
- https://twistedmatrix.com/documents/current/core/howto/tap.html

**Comment by luhkevin** [comment]
Thanks! I think this about covers what I would need.
