### ISSUE TITLE
Possible to add a WSGI instance?

### ISSUE THREAD

**Issue by chuan137** [twisted/klein#106]
How about

```
   k = Klein()
   app = k.wsgi()
```

So that it can be used with gunicorn?

**Comment by notoriousno** [comment]
The underlying Twisted framework does allow you to create WSGI containers, but then you won't be able to do the cool async stuff since WSGI is a synchronous implementation.  If you're hell bent on creating a WSGI app to use with gunicron, then you'll need to introduce your own ``WSGIResource`` and modify ``app.py`` to use your new resource.  Is there any particular feature from gunicron you're looking for?

#### Links ####

 - http://stackoverflow.com/questions/6759115/asynchronous-wsgi-with-twisted
 - http://twistedmatrix.com/documents/current/web/howto/web-in-60/wsgi.html

**Comment by wsanchez** [comment]
I'm closing this ticket because it's not something we expect to support directly in Klein.

Because Twisted is underneath, you may be able to use WSGI as noted by @notoriousno, but that's not a Klein feature.
