### ISSUE TITLE
Support for coroutines.

### ISSUE THREAD

**Issue by wsanchez** [twisted/klein#150]
If one writes an `async def` method, which returns a coroutine, Klein doesn't handle that, so you have to figure out how to turn that into a non-async method that returns a `Deferred`.

For example, I do that with a decorator [here](https://github.com/wsanchez/sample-klein-app/blob/979b02c94fcd8d6caa5a0c40fe5ee575c0ca63a3/src/sample_klein_app/application/dns.py#L20).

It would be nicer if Klein just handled coroutines.

**Comment by notoriousno** [comment]
Here's the gist of what I did a while back in ``app.py``:

``` python
import inspect
from sys import version_info
from twisted.internet.defer import ensureDeferred
# ...

    @wraps(f)
    def _f(instance, request, *a, **kw):
        result = _call(instance, f, request, *a, **kw)
        if version_info.major == 3 and version_info.minor >= 5:
            if inspect.iscoroutine(result):
                return ensureDeferred(result)    # function is awaitable
        return result
```

There's probably a better way to check version numbers, but this is simple. The snippet works great but I couldn't figure out how to make tests for this without throwing build errors. This could only be tested when using Python 3.5+ because anything less than that would raise an error while parsing the source code. Is there a way to tell TravisCI or tox to run different set of tests depending on Python version?

PS
Thank you @wsanchez I'm glad someone cares about this project :)

**Comment by wsanchez** [comment]
@notoriousno thanks for the reference code.

P.S. No worries. What we need now is more people to review PRs.  :-)

**Comment by wsanchez** [comment]
I figured out an only mildly gross way to make the async test work.

However, I'm stuck on [what should be an easier thing to fix](https://github.com/twisted/klein/pull/151#issuecomment-266894669).

**Comment by notoriousno** [comment]
I'm glad the reference code helped (at least I'd like to think it helped ;) you had similar code in your sample code to begin with). I don't have a Python 3.5+ interpreter handy at the moment so I can't help debug at the moment. Made some comments on your PR that may potentially be a blocker.
