### ISSUE TITLE
Azure Web App Deployment

### ISSUE THREAD

**Issue by adiroiban** [twisted/klein#242]
I was looking for a simple way to run a Python based serverless function on the web ... and while I did not found what I want, I found that Azure has a close to serverless IIS Web App available

In the back is a full dedicated Windows with IIS, but you deploy it just from Git :)

I ended up creating a repo to document how to run Klein on Azure. https://github.com/adiroiban/azure-web-app-klein

Not sure if it makes sense to have this as part of the Klein documentation... but just in the case in which someone wants to run Klein on Azure, I left this comment here.

**Comment by glyph** [comment]
Thanks! It might be nice to have this in the docs, but I don't think it's a necessity.  I'm going to close this issue; it's appreciated, but I don't think we need to track it long term.

However, if you'd like to open a PR to add this to the docs, please feel free !  I'm just closing because if you don't do it I don't think we need to make sure someone else does :)
