### ISSUE TITLE
"TypeError: 'Klein' object is not callable" while calling an endpoint from AWS Lambda

### ISSUE THREAD

**Issue by mtzhisham** [twisted/klein#265]
I'm trying to run a simple server 
```
from klein import Klein

app = Klein()

@app.route("/")
def hello(request):
    return "Hello World!"

if __name__ == "__main__":
    run("localhost", 8080)
```

I packaged and uploaded it to AWS Lambda using Zappa, hover i'm getting this after calling the endpoint, any idea why? 
`"{'message': 'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', 'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 452, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/var/task/werkzeug/wrappers.py\", line 939, in from_app\\n    return cls(*_run_wsgi_app(app, environ, buffered))\\n', '  File \"/var/task/werkzeug/test.py\", line 923, in run_wsgi_app\\n    app_rv = app(environ, start_response)\\n', '  File \"/var/task/zappa/middleware.py\", line 70, in __call__\\n    response = self.application(environ, encode_response)\\n', \"TypeError: 'Klein' object is not callable\\n\"]}" `

**Comment by dreid** [comment]
Zappa is expecting that `app` is a wsgi application function but Klein doesn't have support for being run as a wsgi application.

If you just have some Twisted code you want to run you may want to just use Flask and then [crochet](https://crochet.readthedocs.io/) to run the twisted specific code and let flask do the WSGI thing.

It *would* be neat if this worked, but its probably pretty finicky to implement.

I guess it'd look something like:

1. Create a fake `Request` object from wsgi environment.
  - this needs to support all of Request's public API
  - have some way of getting the last finish notification (klein and routes might use `request.notifyFinish()` ) 
2. Invoke `app.resource().render(fake_request)` using [crochet](https://crochet.readthedocs.io) (you'll need some way of getting a deferred that fires on the final finish notification.
3. Make a wsgi response out of the fake `Request`.
4. Return the wsgi response.

Additionally since the reactor will be running in a secondary thread using crochet a queue can be used to implement a streaming response.

**Comment by glyph** [comment]
This is not really a bug in Klein; it's an issue with a mismatch in expectations / types between libraries.  As such I'm going to close it.
